[default]
ident = "Meisaku's Neko"

[default.database.sea_orm]
max_connections = 10
min_connections = 5
connect_timeout = 30

[debug]
secret_key = "K2BfDzg110NMdN2lPv72TMdPcoSWOmkrsOZHBrTjotU="
resend_api_key = "re_FecaS49Z_ApRtxQrZqwVJDf5cMt39DMJE" # Key testing for resend api key
resend_from_email = "meisaku@sawako.dev"
jwt_secret = "oEgwx332WspEDtj1ThSc/Q32vhS0Oqc/rNWHCHSiDWk=" # Key testing for jwt secret
minio_endpoint = "http://127.0.0.1:9000" # Minio testing url instance
minio_access_key = "RcuZaVHIp2eeIGOjqQeS" # Key testing for minio access key
minio_secret_key = "4c7zfHTbrtyVDdaomJZmFWZr03gmnPZPG0ZGYHFx" # Key testing for minio secret key
minio_bucket_name = "meisaku" # Bucket testing for minio

[debug.databases.sea_orm]
url = "postgres://postgres:Sawa-ko-Sawa@localhost:32770/meisaku"
sqlx_logging = true

[release]
secret_key = "oEgwx332WspEDtj1ThSc/Q32vhS0Oqc/rNWHCHSiDWk="